apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/javedkumail/online-boutique-microservice/tree/main/app
    path: release/kubernetes-manifests.yaml
    targetRevision: main
  destination:
    server: https://argocd-aks-cluster-02-dns-2dfpypzu.hcp.centralindia.azmk8s.io:443
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
